mutation createTransaction(
    $description: String!,
    $amount: Float!,
    $currency: String!,
    $status: String!
) {
    createTransaction(
        description: $description,
        amount: $amount, 
        currency: $currency,
        status: $status
    ) {
        id
    }
}  
